# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/ARM-testDeployment

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/IaC-ARMDeployTest'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'IaC_ARM_Template_Dev'
    subscriptionId: 'fb7c94b5-7744-429b-a7ae-db1458359f71'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'IaC-ARMDeployTest-RG'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: '/home/vsts/work/1/a/azuredeploy.json'
    csmParametersFile: '/home/vsts/work/1/a/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'